export const STORE_USER_INFO = "STORE_USER_INFO";
export const STORE_DASBY_UPI = "STORE_DASBY_UPI";
export const STORE_USER_PRIVATE_KEY = "STORE_USER_PRIVATE_KEY";
export const STORE_TWILIO_TOKEN = "STORE_TWILIO_TOKEN";
export const STORE_SELECTED_PATIENT_UPI = "STORE_SELECTED_PATIENT_UPI";
export const STORE_SELECTED_PATIENT_CHAT = "STORE_SELECTED_PATIENT_CHAT";