export const STORE_USER_INFO = "STORE_USER_INFO";
export const STORE_DASBY_UPI = "STORE_DASBY_UPI";
export const STORE_USER_PRIVATE_KEY = "STORE_USER_PRIVATE_KEY";
export const STORE_CHAT_CLIENT = "STORE_CHAT_CLIENT";
export const STORE_PATIENT_DATA = "STORE_PATIENT_DATA";
export const STORE_CURRENT_SELECTED_PATIENT_UPI = "STORE_CURRENT_SELECTED_PATIENT_UPI";
export const CLEAR_STORE = "CLEAR_STORE";